In [41]:
import pandas as pd
import seaborn as sns

df=sns.load_dataset('tips')

In [42]:
from sklearn.preprocessing import LabelEncoder
encoder_time= LabelEncoder()

encoded_data =encoder_time.fit_transform(df['time'])

In [43]:
print('classes', encoder_time.classes_)

classes ['Dinner' 'Lunch']

In [44]:
encoded_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [45]:
for number, category in enumerate(encoder_time.classes_):
    print(category, "--------", number)

Dinner -------- 0
Lunch -------- 1

In [46]:
print('classes', encoder_day.classes_)

NameError: name 'encoder_day' is not defined

In [ ]:
for category, number in zip(encoder_day.classes_, range(len(encoder_day.classes_))):
    print(category, "----------", number)

NameError: name 'encoder_day' is not defined

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe= OneHotEncoder(sparse_output= False)

In [ ]:
ohe.fit_transform(df[['sex','smoker']])

array([[1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.]])

In [ ]:
ohe=OneHotEncoder(sparse_output= False, drop= 'first')
ohe_encoder=ohe.fit_transform(df[['sex','smoker']])
ohe_encoder

array([[0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [0., 0.]])

In [ ]:
import pandas as pd

In [ ]:
df1=pd.DataFrame(ohe_encoder,columns=ohe.get_feature_names_out())
df1

     sex_Male  smoker_Yes
0         0.0         0.0
1         1.0         0.0
2         1.0         0.0
3         1.0         0.0
4         0.0         0.0
..        ...         ...
239       1.0         0.0
240       0.0         1.0
241       1.0         1.0
242       1.0         0.0
243       0.0         0.0

[244 rows x 2 columns]

In [ ]:
pd.concat([df,df1],axis=1)

     total_bill   tip     sex smoker   day    time  size  sex_Male  smoker_Yes
0         16.99  1.01  Female     No   Sun  Dinner     2       0.0         0.0
1         10.34  1.66    Male     No   Sun  Dinner     3       1.0         0.0
2         21.01  3.50    Male     No   Sun  Dinner     3       1.0         0.0
3         23.68  3.31    Male     No   Sun  Dinner     2       1.0         0.0
4         24.59  3.61  Female     No   Sun  Dinner     4       0.0         0.0
..          ...   ...     ...    ...   ...     ...   ...       ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3       1.0         0.0
240       27.18  2.00  Female    Yes   Sat  Dinner     2       0.0         1.0
241       22.67  2.00    Male    Yes   Sat  Dinner     2       1.0         1.0
242       17.82  1.75    Male     No   Sat  Dinner     2       1.0         0.0
243       18.78  3.00  Female     No  Thur  Dinner     2       0.0         0.0

[244 rows x 9 columns]

In [48]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [51]:
log_2=FunctionTransformer(np.log2)
log_2.fit_transform(df['tip'])

0      0.014355
1      0.731183
2      1.807355
3      1.726831
4      1.851999
         ...
239    2.565597
240    1.000000
241    1.000000
242    0.807355
243    1.584963
Name: tip, Length: 244, dtype: float64

In [55]:
import numpy as np
from sklearn.preprocessing import PowerTransformer

In [ ]:
X = np.array([
    [-1],
    [0],
    [3],
    [5],
    [10],
    [50]
])

pt = PowerTransformer(method="yeo-johnson")

X_transformed = pt.fit_transform(X)

print("original:")
print(X.ravel())

print("\ntransformed:")
print(np.round(X_transformed.ravel(), 3))

print("\nlearned lambda:")
print(pt.lambdas_)

original:
[-1  0  3  5 10 50]

transformed:
[-1.54  -0.801 -0.045  0.195  0.571  1.619]

learned lambda:
[0.09126797]

In [60]:
y = np.array([
    [1],
    [0],
    [3],
    [5],
    [10],
    [50]
])

pt = PowerTransformer(method="yeo-johnson")

X_transformed = pt.fit_transform(X)

print("original:")
print(X.ravel())

print("\ntransformed:")
print(np.round(X_transformed.ravel(), 3))

print("\nlearned lambda:")
print(pt.lambdas_)

original:
[-1  0  3  5 10 50]

transformed:
[-1.54  -0.801 -0.045  0.195  0.571  1.619]

learned lambda:
[0.09126797]

In [61]:
import numpy as np
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Henry'],
    'Age': [25, np.nan, 35, 45, np.nan, 29, 41, 38],                   # Numerical with nulls
    'Salary': [50000, 62000, np.nan, 85000, 72000, 48000, np.nan, 67000], # Numerical with nulls
    'Experience_Years': [2, 5, 10, np.nan, 8, 3, 15, 7],             # Numerical with nulls
    'Department': ['IT', 'HR', 'Finance', 'IT', np.nan, 'Marketing', 'Finance', 'HR'], # Categorical with nulls
    'Education': ['Bachelors', 'Masters', 'PhD', 'Bachelors', 'Masters', np.nan, 'Bachelors', 'PhD'], # Categorical with nulls
    'City': ['New York', 'London', 'Paris', np.nan, 'Berlin', 'New York', 'London', 'Paris'], # Categorical with nulls
    'Purchased': ['Yes', 'No', 'No', 'Yes', 'Yes', 'No', np.nan, 'Yes'] # Target (Categorical)
}

df = pd.DataFrame(data)
print(df)
print("\n--- Missing Value Counts ---")
print(df.isnull().sum())

      Name   Age   Salary  Experience_Years Department  Education      City  \
0    Alice  25.0  50000.0               2.0         IT  Bachelors  New York
1      Bob   NaN  62000.0               5.0         HR    Masters    London
2  Charlie  35.0      NaN              10.0    Finance        PhD     Paris
3    David  45.0  85000.0               NaN         IT  Bachelors       NaN
4      Eva   NaN  72000.0               8.0        NaN    Masters    Berlin
5    Frank  29.0  48000.0               3.0  Marketing        NaN  New York
6    Grace  41.0      NaN              15.0    Finance  Bachelors    London
7    Henry  38.0  67000.0               7.0         HR        PhD     Paris

  Purchased
0       Yes
1        No
2        No
3       Yes
4       Yes
5        No
6       NaN
7       Yes

--- Missing Value Counts ---
Name                0
Age                 2
Salary              2
Experience_Years    1
Department          1
Education           1
City                1
Purchased           1
dtype: int64

In [63]:
from sklearn.impute import SimpleImputer

In [68]:
imputer=SimpleImputer(strategy='mean')

df['new_salary'] = imputer.fit_transform(df[['Salary']]).flatten()

In [73]:
imputer=SimpleImputer(strategy='median')

df['new_experience_years'] = imputer.fit_transform(df[['Experience_Years']]).flatten()

In [70]:
df

,Name,Age,Salary,Experience_Years,Department,Education,City,Purchased,new_salary,new_experience_years
0,Alice,25.0,50000.0,2.0,IT,Bachelors,New York,Yes,50000.0,50000.0
1,Bob,NaN,62000.0,5.0,HR,Masters,London,No,62000.0,62000.0
2,Charlie,35.0,NaN,10.0,Finance,PhD,Paris,No,64000.0,64500.0
3,David,45.0,85000.0,NaN,IT,Bachelors,NaN,Yes,85000.0,85000.0
4,Eva,NaN,72000.0,8.0,NaN,Masters,Berlin,Yes,72000.0,72000.0
5,Frank,29.0,48000.0,3.0,Marketing,NaN,New York,No,48000.0,48000.0
6,Grace,41.0,NaN,15.0,Finance,Bachelors,London,NaN,64000.0,64500.0
7,Henry,38.0,67000.0,7.0,HR,PhD,Paris,Yes,67000.0,67000.0

In [79]:


imputer_cat = SimpleImputer(strategy='most_frequent')

df['city'] = imputer.fit_transform(df[['City']]).flatten()

In [80]:
df

,Name,Age,Salary,Experience_Years,Department,Education,City,Purchased,new_salary,new_experience_years,city
0,Alice,25.0,50000.0,2.0,IT,Bachelors,New York,Yes,50000.0,2.0,New York
1,Bob,NaN,62000.0,5.0,HR,Masters,London,No,62000.0,5.0,London
2,Charlie,35.0,NaN,10.0,Finance,PhD,Paris,No,64000.0,10.0,Paris
3,David,45.0,85000.0,NaN,IT,Bachelors,NaN,Yes,85000.0,7.0,London
4,Eva,NaN,72000.0,8.0,NaN,Masters,Berlin,Yes,72000.0,8.0,Berlin
5,Frank,29.0,48000.0,3.0,Marketing,NaN,New York,No,48000.0,3.0,New York
6,Grace,41.0,NaN,15.0,Finance,Bachelors,London,NaN,64000.0,15.0,London
7,Henry,38.0,67000.0,7.0,HR,PhD,Paris,Yes,67000.0,7.0,Paris